# Site settings
author: D Sasser
title: Daniel's Flatiron Blog
header-img: img/home-bg.png
email: danielbsasser@gmail.com
copyright_name: D Sasser
description: > # this means to ignore newlines until "baseurl:"
  A blog for my journey at the Flatiron School 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  dbsasser

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
